[package]
name = "nrobloxs/basicstate"
description = "A lightweight Roblox state machine library"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
